### ISSUE TITLE
Issue when changing facebook session

### ISSUE THREAD

**Issue by blancomaberino** [GromNaN/FacebookServiceProvider#5]
Hi,

I am not sure if this should be treated as an issue but, in anycase, i am posting it here.

The problem is that when i logout from facebook and log in with another account from the same browser, the facebook session is still there (for the old user).

Is there any way to check if the user logged in to the app is the same that is currently logged in to facebook? I tried to check using the function getUser from facebook but, as the session was never destroyed, it retrieves the old user.

Any idea?

Thanks.

Regards,

Marcelo

**Comment by GromNaN** [comment]
Hi @blancomaberino,

If you want to be sure that the user logger to you application is the one logged in Facebook, you should use the SDK JavaScript and get the current user.
